### PR TITLE
close connections properly even if init step failed

### PR DESCRIPTION
**Pull request by velimir**
## Proposed Changes

Connections are not closed gracefully if destination or source
initialisation throws an exception.
Connections are created a bit earlier before src/dst are initialised.
If for any reason init phase fails, connection pids will be lost and
shovel protocols won’t be able to close them as they are not preserved
within a state.

## Types of Changes

- [x] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Note that you can extract the connection function that would do error handling and reuse it for each side.

**Comment by michaelklishin** [comment]
I am happy to take over/finish this PR.

**Comment by velimir** [comment]
> All we care about is returnning Config1 or Config2 early in case of an error or exception, right?

Correct. Config1 and Config2 if error or exception occurs further down `handle_cast` execution.

> I am happy to take over/finish this PR.

Thanks. That's ok. Let me try to brush up my Erlang :)

**Comment by michaelklishin** [comment]
Your Erlang is fine. It's just that I am not intelligent enough to reason about casts to self a year or two from now when I'd have to take a look at that code next 🙈

**Comment by michaelklishin** [comment]
@velimir thank you!

Backported to `v3.7.x`.

**Comment by michaelklishin** [comment]
This init scheme has a side effect of #60. We are investigating.

**Pull request merged**
